### PR TITLE
Optimizable view

### PR DESCRIPTION
**Pull request by vbfox**
Use the inversion of the view and model parameters in https://github.com/fable-elmish/elmish/pull/131 to allow to optimize views.

I also changed the parameter order in lazyView2 and friend to match (It's not necessary as the optimization isn't possible while using them only `lazyViewWith` allow that but It felt strange to have them non-consistent)

### CODE REVIEW

**Comment by vbfox** [comment]
Ah also I didn't use the new capability in the samples as I feel that it's more of an advanced topic.

I'll do some blog posts on optimizing React in Fable & Fable.Elmish I think and when I have clear ideas and everything works i'll try to add a page to the documentation on that topic.

**Comment by vbfox** [comment]
@et1975 Is it voluntary for the current version in master to have `withReactUnoptimized` instead of `withReact` ? (And also the comment is a little off)

**Comment by et1975** [comment]
Just a result of merging the same commits from two different PRs, I'm cleaning this up.

**Comment by et1975** [comment]
Released as 2.0.0-beta-1, would be curious to see the performance gains, if any... maybe using something like this https://github.com/et1975/react-angular-ember-elm-performance-comparison.

**Pull request merged**
