### PR TITLE
Add withReactHydrate

### PR DESCRIPTION
**Pull request by zaaack**
Since fable-react is now [supported server-side rendering](https://github.com/fable-compiler/fable-react/pull/65), I think we can add React's new ssr API ([.hydrate](https://reactjs.org/docs/react-dom.html#hydrate)) for elmish-react.

Currently I only add a version without raf optimization in this PR, not sure I should add a raf optimized version like `withReactHydrayeAnimationFrameOptimized` (maybe it's too long?)

### CODE REVIEW

**Comment by et1975** [comment]
Looks like you'll need to add the new paket (bootstrapper) to the PR to get the CI to build - with [5.141.0](https://github.com/fsprojects/Paket/releases/tag/5.141.0) or later release.

**Comment by zaaack** [comment]
@et1975 ping...

**Comment by et1975** [comment]
Thank you!

**Comment by et1975** [comment]
Released as 2.0.0-beta-2

**Pull request merged**
